apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: new-application-3-main
      imagePullPolicy: Always
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: new-application-3
    version: v0.0.1
    applicationId: app_1769f196-ea78-428a-bcff-1ad1c65c6763
    projectId: project_779082ee-0a6a-4252-9cc2-3ed6e001565f
    organizationId: org_99bfadb5-996a-47d5-a5fc-442c14a28627
    environmentId: env_50270242-b404-4bac-9b8e-e90fb7d0bb1d
    environmentName: staging
  horizontalAutoScalingRules: []
  volumes: []
  type: Job
  name: new-application-3
  cronTab: ''
  serviceType: ClusterIP
  namespace: new-project-staging
